CREATE OR REPLACE EDITIONABLE TRIGGER TRG_BEFORE_INSERT_EMPLOYEES
BEFORE INSERT ON employees
FOR EACH ROW
BEGIN
  IF :NEW.salary IS NULL THEN
    :NEW.salary := 30000;
  END IF;
END;
/
ALTER TRIGGER TRG_BEFORE_INSERT_EMPLOYEES ENABLE;

